language: node_js
node_js:
  - 6.1.x
cache:
  directories:
  - node_modules
install:
  - npm install
  - npm run build
deploy:
  provider: heroku
  app: fccgitterapp
  api_key:
    secure: nhuyNdJrr+7qymY9dOyEWPfH1T8SdUs66AAlY8wSrHuzZfuGc094E8Jsr2+14Ho65r85f2Rh5brN3lH4C9iZGtqCLVDY5ikVSxS4JDSl88kd6mBV601ydVV/6R1kD5m3CxKVrr6wh3rVyBL5MbBEbdCj6AqHwUHd1UTK75y85Uf+ukUmFwA2BmOlU8CWyhBvh27NDhW1UAnDnrEFRFdVGISoBMTjoJhtrRNnI38AlvK+OD7NL5dF+PnWLtg8aSgkgdd0Y7DPo7U4twkLNSzSYn2txcYqInZHLZJxgf5yDh/Nr9KPqMm6YraOrE02YGcDhOlNYW+J9j/Z8MC2DbCUzVdsF9TyakaYy1K+TQoLNXO8gFs2d6iq6fCpn2Bazl7ML6mzL+XbTnCyfWsERygKnVjHmiskXsqPxUN32oCmDYNl8NpT9Q3RJNeC4lQ6t9Cf6q6+ILOUJCentUEKBLvtREsT2GTL3WgXUA7se3RIzR6fAROdP3bJcdBQoWlkGUswAi01JdUjddDREm9GM4SxhSfLtRc4wpu7F1LCfFsj7GYJ84cndVn/XLexaIitn9c0Uwb80hQQxkRitZHu/L1VrHJO4tLCVoRR0LD3uRSHZq1H4g5eet7gNB1gZByRnGiUSOlK5cfHP/wNgEuoRLOixLyb+9Z0Cs7D5a20HJ1z0+I=
branches:
  only:
  - dev
